%%{init: {"flowchart": {"curve": "linear"}}}%%
graph LR
    subgraph UI [Màn hình / Chức năng]
        F[Đổ xăng]
        M[Bảo dưỡng & Phụ tùng]
        S[Thống kê / Chi phí]
        V[Xe của tôi]
        A[Xác thực]
    end

    subgraph Local [Cơ sở dữ liệu: SQLite Local]
        T_F[(fuel_entries)]
        T_M[(maintenance_entries)]
        T_V[(vehicles)]
    end

    subgraph Cloud [Máy chủ: Firebase Cloud]
        FS[(Cloud Firestore)]
        ST[(Firebase Storage)]
        FA[(Firebase Auth)]
    end

    F -->|Lưu Offline| T_F
    M -->|Lưu chữ Offline| T_M
    M -->|Upload Ảnh hóa đơn| ST
    
    S -.->|Truy vấn gộp| T_F
    S -.->|Truy vấn gộp| T_M
    
    V -->|Lưu thông tin xe| T_V
    V -->|Upload Ảnh xe| ST
    
    A -->|Cấp UID| FA
    FA -.->|Gắn UID| T_V
    
    T_F <-->|Auto Sync| FS
    T_M <-->|Auto Sync| FS
    T_V <-->|Auto Sync| FS
